declare const styles: {
  readonly widgetTheme: string;
  readonly widgetWrapper: string;
  readonly chatContainer: string;
  readonly chatbox: string;
  readonly chatInput: string;
  readonly footer: string;
  readonly errorMessage: string;
  readonly muteButton: string;
  readonly muted: string;
  readonly submitBtn: string;
  readonly footerLogo: string;
  readonly footerText: string;
  readonly footerContent: string;
  readonly streamButtonContainer: string;
  readonly streamButton: string;
  readonly streamButtonRing: string;
  readonly toggleContainer: string;
  readonly toggleButton: string;
  readonly active: string;
  readonly toggleIcon: string;
  readonly toggleText: string;
  readonly mainWrapper: string;
  readonly contentContainer: string;
  readonly messageContainer: string;
  readonly messageBubble: string;
  readonly assistantMessage: string;
  readonly userMessage: string;
  readonly inputContainer: string;
  readonly chatForm: string;
  readonly sendButton: string;
  readonly formContainer: string;
  readonly formField: string;
  readonly submitButton: string;
};

export default styles;