"""Add CacheEntry and RetellAIEvent models

Revision ID: ae5e2e07e0d7
Revises: c2271b8e16d7
Create Date: 2024-08-06 22:13:24.924048

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ae5e2e07e0d7'
down_revision = 'c2271b8e16d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
