"""Add CacheEntry and RetellAIEvent models

Revision ID: c2271b8e16d7
Revises: c3bcd635fb6a
Create Date: 2024-08-06 16:35:17.307230

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c2271b8e16d7'
down_revision = 'c3bcd635fb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retellaicalls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retellaicalls_event_id'), 'retellaicalls', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retellaicalls_event_id'), table_name='retellaicalls')
    op.drop_table('retellaicalls')
    # ### end Alembic commands ###
