"""Add CacheEntry and RetellAIEvent models

Revision ID: c3bcd635fb6a
Revises: 9c0a54914c78
Create Date: 2024-08-06 13:25:50.017389

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c3bcd635fb6a'
down_revision = '9c0a54914c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cacheentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cacheentry_key'), 'cacheentry', ['key'], unique=False)
    op.create_table('retellaievent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retellaievent_event_id'), 'retellaievent', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retellaievent_event_id'), table_name='retellaievent')
    op.drop_table('retellaievent')
    op.drop_index(op.f('ix_cacheentry_key'), table_name='cacheentry')
    op.drop_table('cacheentry')
    # ### end Alembic commands ###
